apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    name: nv.httpbin.default
    namespace: default
  spec:
    dlp:
      settings: []
      status: true
    egress: []
    file: []
    ingress:
    - action: allow
      applications:
      - HTTP
      name: nv.httpbin.default-ingress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria: []
        name: nodes
        original_name: ""
    process:
    - action: allow
      allow_update: false
      name: dash
      path: /bin/dash
    - action: allow
      allow_update: false
      name: gunicorn
      path: /usr/bin/python3.6
    - action: allow
      allow_update: false
      name: ldconfig.real
      path: /sbin/ldconfig.real
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    - action: allow
      allow_update: false
      name: uname
      path: /bin/uname
    process_profile:
      baseline: zero-drift
    target:
      policymode: Discover
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: httpbin.default
        - key: domain
          op: =
          value: default
        name: nv.httpbin.default
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: null
