apiVersion: neuvector.com/v1
kind: NvAdmissionControlSecurityRule
metadata:
  name: local
spec:
  config:
    client_mode: service      #coming services like deployment or image scanning related
    enable: true
    mode: protect              #there can be two modes protect and monitor
  rules:
  - action: deny              #allow or deny
    criteria:
    - name: cveHighWithFixCount     #if that application container high severity wit fixed count so need to deny that request 
      op: '>='
      value: "12"
